services:
  backend:
    image: dhruv2k3/basal-backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - basal-net
networks:
  basal-net:
    driver: bridge